CREATE TABLE IF NOT EXISTS "Users" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY,
  "FirstName" text NOT NULL,
  "SecondName" text NOT NULL,
  "Email" text NOT NULL,
  "Password" text NOT NULL,
  CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
